import {
  loadPlatformPackage,
  platformPackageName,
  type PlatformPackageName,
} from './platform-map';

declare const process: { readonly platform: string; readonly arch: string };

type PlatformRuntimeModule = Record<string, unknown>;

async function importPlatformPackage(packageName: PlatformPackageName): Promise<PlatformRuntimeModule> {
  switch (packageName) {
    case '@forgeax/game-runtime-darwin-arm64':
      // @ts-ignore Generated by the native release job before Universal is built.
      return import('@forgeax/game-runtime-darwin-arm64');
    case '@forgeax/game-runtime-win32-x64':
      // @ts-ignore Generated by the native release job before Universal is built.
      return import('@forgeax/game-runtime-win32-x64');
    case '@forgeax/game-runtime-linux-x64':
      // @ts-ignore Generated by the native release job before Universal is built.
      return import('@forgeax/game-runtime-linux-x64');
  }
}

const selected = await loadPlatformPackage(
  { platform: process.platform, arch: process.arch },
  importPlatformPackage,
);

function requiredExport<T>(name: string, predicate: (value: unknown) => boolean): T {
  const value = selected[name];
  if (!predicate(value)) {
    throw new Error(`${platformPackageName()} does not expose the required Runtime API: ${name}`);
  }
  return value as T;
}

type RuntimeFunction = (...args: unknown[]) => unknown;
const runtimeFunction = (name: string): RuntimeFunction => requiredExport(name, (value) => typeof value === 'function');

export const runtimeDistribution = requiredExport<Record<string, unknown>>(
  'runtimeDistribution',
  (value) => typeof value === 'object' && value !== null,
);
export const ensureRuntime = runtimeFunction('ensureRuntime');
export const resolveInstalledRuntime = runtimeFunction('resolveInstalledRuntime');
export const runtimeCacheRoot = runtimeFunction('runtimeCacheRoot');
export const launcherForRuntime = runtimeFunction('launcherForRuntime');
export const runtimeEnvironment = runtimeFunction('runtimeEnvironment');
export const allocatePort = runtimeFunction('allocatePort');
export const allocateRuntimePorts = runtimeFunction('allocateRuntimePorts');
export const loadRuntimeManifest = runtimeFunction('loadRuntimeManifest');
export const engineSdkRoot = runtimeFunction('engineSdkRoot');
export const installEngineSdk = runtimeFunction('installEngineSdk');

export { PLATFORM_PACKAGES, loadPlatformPackage, platformPackageName } from './platform-map';
export default runtimeDistribution;
