#!/usr/bin/env bash
# seed-agent-avatars.sh — populate every agent plugin's avatar/ directory
# from the插画师交付的动态差分资源目录.
#
# Usage:
#   bash scripts/seed-agent-avatars.sh                          # default src
#   FORGEAX_PORTRAIT_SRC=/path/to/output_动态差分 bash ...     # override src
#   bash scripts/seed-agent-avatars.sh --dry-run                # preview only
#   bash scripts/seed-agent-avatars.sh --force                  # overwrite even if size matches
#
# Mapping table (27 agents → 11 portrait sets) is below in MAP_*. Every agent
# becomes self-contained: <plugin>/avatar/ holds its own copy of 9 webm + a
# generic AVATAR.md state-machine rules file. Smart fallback applies for
# agents without dedicated portraits (forgeax-default → Arin; animator-2d
# / character-designer-2d / vfx-artist-3d / lowpoly → Iro;
# reel-storyboard / reel-video / reel-visual → reia, REIA 的 3 个专业子智能体
# 暂时复用导演本人的 portrait, 等插画师补齐后用 --force 一键替换).
# 场景资产流水线 (director / sino / mira) 共用 haru多表情 专属 portrait
# (2026-06-24).
#
# Idempotent: skips files whose size already matches the source (unless --force).
# Safe to re-run after插画师 ships updated webms.
#
# See ADR-0019 (docs/decisions/0019-agent-avatar-statemachine.md) for rationale.
#
# UX follow-up note (ADR-0019 §9, P5 deferred): the smart-fallback strategy
# above intentionally makes 8 coder agents + 5 art sub-role agents + 3 reel
# sub-agents share three placeholder portraits — visually that means catalog
# views currently show ≥4 capsules with identical artwork. P5 will collapse
# same-portrait families
# into one "group head" capsule + click-down popover in the 3 catalog views
# (ChatAgentCapsule, MainArea/WorkbenchMode AgentsMainArea, wb-agent-persona
# iframe). Sidebar/AgentsPanel and SettingsPanel/SectionsRegister stay flat
# (they serve different purposes — see ADR §9 scope table). Once illustrator
# delivers dedicated portraits for any of the placeholder-mapped agents,
# re-running this script with --force shrinks the same-portrait family
# naturally and the corresponding group config entry should be edited.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

SRC="${FORGEAX_PORTRAIT_SRC:-/Users/you/Desktop/forgeax数字生命美术资产/output_动态差分}"
DST_ROOT="$ROOT/packages/marketplace/extensions"
DRY_RUN=0
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --force)   FORCE=1 ;;
    -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

[ -d "$SRC" ] || { echo "ERROR: source folder not found: $SRC" >&2; exit 1; }
[ -d "$DST_ROOT" ] || { echo "ERROR: dst not found: $DST_ROOT" >&2; exit 1; }

# 24 agents → 10 portrait sets (see ADR-0019 §Decision §3-4).
# Lines: "agent-id<TAB>portrait-folder-name<TAB>fallback?"
# fallback? = "self" (dedicated) | "<sourceAgent>" (smart fallback)
read -r -d '' MAP <<'EOF' || true
arin	Arin多表情	self
forgeax-default	Arin多表情	arin
iori	Iori多表情	self
iro	Iro多表情	self
mira	haru多表情	self
director	haru多表情	self
sino	haru多表情	self
animator-2d	Iro多表情	iro
character-designer-2d	Iro多表情	iro
vfx-artist-3d	Iro多表情	iro
lowpoly	Iro多表情	iro
kotone	kotone多表情	self
lock	lock多表情	self
reia	reia多表情	self
reel-storyboard	reia多表情	reia
reel-video	reia多表情	reia
reel-visual	reia多表情	reia
suzu	suzu多表情	self
tsumugi	tsumugi多表情	self
yevi	yevi多表情	self
cc-coder	通用coder多表情	self
claude-code-default	通用coder多表情	common-coder
codex-default	通用coder多表情	common-coder
cursor-default	通用coder多表情	common-coder
kaede	通用coder多表情	common-coder
kumo	通用coder多表情	common-coder
mochi	通用coder多表情	common-coder
rin	通用coder多表情	common-coder
sakura	通用coder多表情	common-coder
EOF

# AVATAR.md content — identical across all 24 agents (规则跨 agent 通用;
# 资源差异由 webm 自身承载, 不需要逐 agent 改规则). See ADR-0019 §Decision §5.
AVATAR_MD=$(cat <<'AVAMD'
---
# Agent avatar state machine — 9 emotion bucket scheme
# See ADR-0019: docs/decisions/0019-agent-avatar-statemachine.md
# Generated by scripts/seed-agent-avatars.sh — edit ADR + script if changing structure.

default: 期待
fallback: 期待

# Universal event → emotion bucket (UI hook 把底层 ~43 个事件归并为 9 类粒度).
# 小事件增减只影响 UI hook 的归并逻辑, 不影响这张表.
events:
  run_start:          期待
  reasoning_active:   专注
  speaking_active:    开心
  tool_active:        认真
  sub_agent_active:   安心
  production_signal:  自豪
  metabolism_signal:  疲惫
  error_signal:       难过
  media_active:       好奇
  run_end:            期待

# 优先级 (数字越小越高); 多事件并发时取顶层 emotion.
priority:
  难过: 1
  安心: 2
  认真: 3
  自豪: 4
  专注: 5
  开心: 6
  疲惫: 7
  好奇: 8
  期待: 10
---

# Avatar State Machine

| state | file          | loop  | fadeInMs | onEnd | onEndAfterMs |
|-------|---------------|-------|----------|-------|--------------|
| 期待  | 01_期待.webm  | true  | 200      |       |              |
| 专注  | 02_专注.webm  | true  | 100      |       |              |
| 开心  | 03_开心.webm  | true  | 100      |       |              |
| 认真  | 04_认真.webm  | true  | 100      |       |              |
| 安心  | 05_安心.webm  | true  | 100      |       |              |
| 自豪  | 06_自豪.webm  | false | 100      | 期待  | 1500         |
| 疲惫  | 07_疲惫.webm  | false | 200      | 期待  | 2000         |
| 难过  | 08_难过.webm  | false | 0        | 期待  | 5000         |
| 好奇  | 09_好奇.webm  | true  | 100      |       |              |

## 备注

- 本文件由 `scripts/seed-agent-avatars.sh` 在每个 agent plugin 的 `avatar/` 子目录下生成.
- 状态机规则跨所有 agent 通用, 美术差异由 webm 内容自身承载.
- 5 个美术细分 agent (mira / animator-2d / character-designer-2d / vfx-artist-3d / lowpoly)
  + planner agent (forgeax-default) + 3 个 REIA 子智能体 (reel-storyboard / reel-video /
  reel-visual) 当前临时引用其他角色的 portrait, 待插画师补齐后用
  `bash scripts/seed-agent-avatars.sh --force` 一键替换.
AVAMD
)

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m⚠ %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; }

bold "[seed-agent-avatars]"
[ "$DRY_RUN" = "1" ] && warn "DRY-RUN mode — no files will be written"
[ "$FORCE" = "1" ]   && warn "FORCE mode — every webm will be overwritten"
echo "  src: $SRC"
echo "  dst: $DST_ROOT/agent-<id>/avatar/"
echo ""

# stat -c (linux) vs stat -f (mac BSD) — use wc as portable fallback.
filesize() { wc -c < "$1" | tr -d ' '; }

copied=0; skipped=0; missing=0
declare -a SUMMARY

while IFS=$'\t' read -r agent portrait fallback; do
  [ -n "$agent" ] || continue
  src_dir="$SRC/$portrait"
  # Resolve the agent's on-disk home across the three live layouts:
  #   flat standalone dir        extensions/agent-<id>/
  #   kind-bucketed (mkt#64)     extensions/agent/agent-<id>/
  #   wb-reel bundled (M4)       extensions[/workbench]/wb-reel/agents/<id>/
  agent_home=""
  for cand in \
    "$DST_ROOT/agent-$agent" \
    "$DST_ROOT/agent/agent-$agent" \
    "$DST_ROOT/wb-reel/agents/$agent" \
    "$DST_ROOT/workbench/wb-reel/agents/$agent"; do
    if [ -d "$cand" ]; then agent_home="$cand"; break; fi
  done
  dst_dir="$agent_home/avatar"

  if [ ! -d "$src_dir" ]; then
    fail "source portrait folder missing: $portrait (for agent-$agent)"
    missing=$((missing + 1))
    continue
  fi
  if [ -z "$agent_home" ]; then
    warn "agent dir missing: agent-$agent — skip"
    continue
  fi

  [ "$DRY_RUN" = "1" ] || mkdir -p "$dst_dir"

  agent_copied=0; agent_skipped=0
  for src in "$src_dir"/*.webm; do
    [ -e "$src" ] || continue
    name="$(basename "$src")"
    dst="$dst_dir/$name"
    if [ "$FORCE" != "1" ] && [ -f "$dst" ] && [ "$(filesize "$src")" = "$(filesize "$dst")" ]; then
      agent_skipped=$((agent_skipped + 1))
      continue
    fi
    if [ "$DRY_RUN" = "1" ]; then
      agent_copied=$((agent_copied + 1))
    else
      cp "$src" "$dst"
      agent_copied=$((agent_copied + 1))
    fi
  done

  # AVATAR.md (overwrite if differs, idempotent).
  avatar_md="$dst_dir/AVATAR.md"
  if [ "$DRY_RUN" != "1" ]; then
    if [ "$FORCE" = "1" ] || [ ! -f "$avatar_md" ] || ! diff -q <(printf '%s' "$AVATAR_MD") "$avatar_md" >/dev/null 2>&1; then
      printf '%s' "$AVATAR_MD" > "$avatar_md"
    fi
  fi

  copied=$((copied + agent_copied))
  skipped=$((skipped + agent_skipped))

  tag="$fallback"
  [ "$tag" = "self" ] && tag="—"
  SUMMARY+=("$(printf '  %-25s ← %-20s  copied:%d skipped:%d  fallback:%s' "agent-$agent" "$portrait" "$agent_copied" "$agent_skipped" "$tag")")
done <<< "$MAP"

echo "Per-agent breakdown:"
for line in "${SUMMARY[@]}"; do echo "$line"; done
echo ""
ok "total webm copied:  $copied"
ok "total webm skipped: $skipped (already up-to-date)"
[ "$missing" -gt 0 ] && fail "$missing portrait folders missing — fix \$FORGEAX_PORTRAIT_SRC"

if [ "$DRY_RUN" = "1" ]; then
  warn "DRY-RUN — re-run without --dry-run to apply"
fi
