// Ambient module shims for the FEW @forgeax/engine-* packages that ship NO
// TypeScript declarations even after a full engine build (their tsup config is
// dts:false and `tsc -b` emits nothing for them). This MIRRORS the editor
// submodule's SSOT shim at packages/editor/types/forgeax-engine-shims.d.ts —
// keep the two in sync when the engine's declaration-less set changes.
//
// studio's tsconfig pulls editor-core sources into its program via workspace
// symlinks (transitively through @forgeax/interface and @forgeax/editor-*).
// Every OTHER engine package (runtime / ecs / types / gltf / pack / …) now
// resolves to its real dist/*.d.ts, generated by `tsc -b` in scripts/prepare.ts
// step 3 — do NOT bare-declare those here or the explicit `any` shadows the
// real types and trips TS2709. Only the three genuinely declaration-less
// packages below need a shim.
//
// WHY EXPLICIT, NOT BARE: a bodyless `declare module 'X';` erases X to `any`,
// so tsc stops checking named imports from it — that is how a non-existent
// `{ Socket }` import once slipped past typecheck and crashed at the user's
// runtime (AGENTS.md editor anti-pattern #5). Each block is an allowlist:
// importing a name not declared here still fails typecheck.
//
// When engine-project / engine-fbx start shipping real .d.ts, delete the
// matching block here AND in the editor SSOT.

// engine-project — value + type space. store.ts / open-project.ts import both
// runtime values (loadGameProject / FORGE_JSON / GameProjectError) AND types
// (`type GameProject`). These are REAL engine exports (engine-project/src/
// {schema,errors}.ts) — the module just ships no .d.ts.
declare module '@forgeax/engine-project' {
  export const loadGameProject: any;
  export const loadGameProjectSync: any;
  export const resolveDefaultScene: any;
  export const validateGameProject: any;
  export const GameProjectSchema: any;
  export const GameProjectError: any;
  export const FORGE_JSON: string;
  export type GameProject = any;
  export type ResolvedScene = any;
  export type GameProjectErrorCode = any;
  export type GameProjectErrorDetail = any;
}

// engine-fbx — ufbx WASM runtime (initFbxWasm / parseFbx / isFbxWasmReady) PLUS
// the parse-*.ts helpers, since the engine collapsed the former
// @forgeax/engine-fbx-wasm package INTO @forgeax/engine-fbx (feat-20260704-
// collapse-fbx-to-ufbx). It DOES ship real .d.ts after a full `tsc -b` engine
// build, but studio builds engine with tsup-only for the .mjs, so keep this in
// the declaration-less set to match the editor SSOT. value + type space —
// fbx-cook imports the wasm runtime, the parse-*.ts functions, and the FbxRaw* types.
declare module '@forgeax/engine-fbx' {
  export const initFbxWasm: any;
  export const parseFbx: any;
  export const isFbxWasmReady: any;
  export const parseMesh: any;
  export const parseScene: any;
  export const parseMaterial: any;
  export const parseSkeleton: any;
  export const parseSkin: any;
  export const parseAnimationClips: any;
  export type FbxRawDocument = any;
  export type FbxRawMesh = any;
  export type FbxRawNodes = any;
  export type FbxRawMaterial = any;
  export type FbxRawSkeletonDoc = any;
  export type FbxRawSkinDoc = any;
  export type FbxRawAnimDoc = any;
}
